export const MenuItems=[
    {icon:'ri-home-6-line', label: 'Hospital Dashboard', path: '/hospital-dashboard', isOpen: false,  children: []},
    {icon:'ri-home-smile-2-line', label: 'Medical Dashboard', path: '/medical-dashboard',isOpen: false,  children: []},
    {icon:'ri-home-5-line', label: 'Dentist Dashboard', path: '/dentist-dashboard',isOpen: false,  children: []},
    {icon: 'ri-stethoscope-line', label: 'Doctors', path: '/doctors',isOpen: false,  children: [
      {icon: '', label: 'Doctors Dashboard', path: '/doctors/doctors-dashboard'},
      {icon: '', label: 'Doctors List', path: '/doctors/doctors-list'},
      {icon: '', label: 'Doctors Cards', path: '/doctors/doctors-cards'},
      {icon: '', label: 'Doctors Profile', path: '/doctors/doctors-profile'},
      {icon: '', label: 'Add Doctor', path: '/doctors/add-doctor'},
      {icon: '', label: 'Edit Doctor', path: '/doctors/edit-doctor'},
    ]},
    {icon:'ri-heart-pulse-line', label: 'Patients', path: '/patients',isOpen: false,  children: [
      {icon: '', label: 'Patients Dashboard', path: '/patients/patients-dashboard'},
      {icon: '', label: 'Patients List', path: '/patients/patients-list'},
      {icon: '', label: 'Add Patients', path: '/patients/add-patients'},
      {icon: '', label: 'Edit Patient Details', path: '/patients/edit-patients-details'},
    ]},
    {icon:'ri-nurse-line', label: 'Staff', path: '/staff',isOpen: false,  children: [ 
      {icon: '', label: 'Staff List', path: '/staff/staff-list'},
      {icon: '', label: 'Add Staff', path: '/staff/add-staff'},
      {icon: '', label: 'Edit Staff Detail', path: '/staff/edit-staff-detail'},
    ]},
    {icon:'ri-dossier-line', label: 'Appointments', path: '/appointments', isOpen: false,  children: [
      {icon: '', label: 'Appointments Dashboard', path: '/appointments/appointments1'},
      {icon: '', label: 'Appointments List', path: '/appointments/appointments-list'},
      {icon: '', label: 'Book Appointment', path: '/appointments/book-appointment'},
      {icon: '', label: 'Edit Appointment', path: '/appointments/edit-appointment'},
     ]},
     {icon: 'ri-building-2-line', label: 'Departments', path: '/departments',isOpen: false,  children: [
      {icon: '', label: 'Departments List', path: '/departments/department-list'},
      {icon: '', label: 'Add Department', path: '/departments/add-department'},
      {icon: '', label: 'Edit Department', path: '/departments/edit-department'},
     ]},
     {icon: 'ri-secure-payment-line', label:'Accounts', path: '/accounts', isOpen: false, children: [
      {icon:'', label:'Income', path: '/accounts/income'},
      {icon:'', label:'Payments', path: '/accounts/payment'},
      {icon:'', label:'Invoices', path: '/accounts/invoices'},
      {icon:'', label:'Invoice Details', path: '/accounts/invoice-detail'},
      {icon:'', label:'Create Invoice', path: '/accounts/create-invoice'},
      {icon:'', label:'Expenses', path: '/accounts/expenses'},
     ]},
     {icon:'ri-group-2-line', label:'Human Resources', path: '/human-resources',isOpen: false,  children: [
      {icon:'', label:'HR Approvals', path: '/human-resources/hr-approvals'},
      {icon:'', label:'Attendance', path: '/human-resources/attendance'},
      {icon:'', label:'Staff Leaves', path: '/human-resources/staff-leaves'},
      {icon:'', label:'Holidays', path: '/human-resources/holidays'},
     ]},
     {icon:'ri-money-dollar-circle-line', label:'Salaries', path: '/salaries', isOpen: false, children: [
      {icon:'', label:'Salary List', path: '/salaries/salary-list'},
      {icon:'', label:'Payslip', path: '/salaries/payslip'},
     ]},
     {icon:'ri-hotel-bed-line', label:'Rooms', path:'/rooms', isOpen: false, children:[
      {icon:'', label:'Statistics', path:'/rooms/statistics'},
      {icon:'', label:'Rooms Alloted', path:'/rooms/rooms-alloted'},
      {icon:'', label:'Rooms By Department', path:'/rooms/rooms-by-department'},
      {icon:'', label:'Available Rooms', path:'/rooms/available-rooms'},
      {icon:'', label:'Book Room', path:'/rooms/book-room'},
      {icon:'', label:'Add Room', path:'/rooms/add-room'},
      {icon:'', label:'Edit Room', path:'/rooms/edit-room'},
    ]},
    {icon:'ri-car-washing-line', label:'Ambulance', path:'/ambulance',isOpen: false,  children:[
      {icon:'', label:'Ambulance List', path:'/ambulance/ambulance-list'},
      {icon:'', label:'Add Ambulance', path:'/ambulance/add-ambulance'},
      {icon:'', label:'Edit Ambulance', path:'/ambulance/edit-ambulance'},
      {icon:'', label:'Ambulance Call List', path:'/ambulance/ambulance-call-list'},
    ]},
    {icon:'ri-calendar-line', label:'Event Management', path:'/event-management',isOpen: false,  children:[]},
    {icon:'ri-tent-line', label:'Gallery', path:'/gallery',isOpen: false,  children:[]},
    {icon:'ri-news-line', label:'News & updates', path:'/news-updates', isOpen: false, children:[]},
    {icon:'ri-color-filter-line', label:'UI Elements', path:'/ui-elements', isOpen: false, children:[
      {icon:'', label:'Alterts', path:'/ui-elements/alerts'},
      {icon:'', label:'Avatars', path:'/ui-elements/avatars'},
      {icon:'', label:'Badges', path:'/ui-elements/badges'},
      {icon:'', label:'Buttons', path:'/ui-elements/buttons'},
      {icon:'', label:'Button Groups', path:'/ui-elements/button-group'},
      {icon:'', label:'Cards', path:'/ui-elements/cards'},
      {icon:'', label:'Adavnced Cards', path:'/ui-elements/advanced-cards'},
      {icon:'', label:'Dropdowns', path:'/ui-elements/dropdowns'},
      {icon:'', label:'List Items', path:'/ui-elements/list-items'},
      {icon:'', label:'Progress Bars', path:'/ui-elements/progress-bars'},
      {icon:'', label:'Placeholders', path:'/ui-elements/placeholders'},
      {icon:'', label:'Spinners', path:'/ui-elements/spinners'},
     ]},
     {icon:'ri-notification-badge-line', label:'Jquery Components', path:'/jquery-components', isOpen: false, children:[
      {icon:'', label:'Accordions', path:'/jquery-components/accordions'},
      {icon:'', label:'Carousel', path:'/jquery-components/carousel'},
      {icon:'', label:'Modals', path:'/jquery-components/modals'},
      {icon:'', label:'Popovers', path:'/jquery-components/popovers'},
      {icon:'', label:'Tabs', path:'/jquery-components/tabs'},
      {icon:'', label:'Tooltips', path:'/jquery-components/tooltips'},
    ]},
    {icon:'ri-terminal-window-line', label:'Forms', path:'/forms',isOpen: false,  children:[
      {icon:'', label:'Form Inputs', path:'/forms/form-inputs'},
      {icon:'', label:'Checkbox & Radio', path:'/forms/checkbox-radio'},
      {icon:'', label:'File Inputs', path:'/forms/file-input'},
      {icon:'', label:'Validations', path:'/forms/validations'},      
      {icon:'', label:'Date Time Pickers', path:'/forms/datetime-pickers'},
      {icon:'', label:'Input Masks', path:'/forms/input-masks'},
      {icon:'', label:'Input Tags', path:'/forms/input-tags'},
    ]},
    {icon:'ri-table-line', label:'Tables', path:'/tables', isOpen: false, children:[]},
    {icon:'ri-bar-chart-line', label:'Graphs', path:'/graphs', children:[
      {icon:'', label:'Apex Graphs', path:'/graphs/apex-graphs'},
      {icon:'', label:'Morris Graphs', path:'/graphs/morris-graphs'},
     ]},
     {icon:'ri-road-map-line', label:'Vector Maps', path:'/vactor-maps', isOpen: false, children:[]},
     {icon:'ri-send-plane-2-line', label:'Icons', path:'/icons', children:[]},
     {icon:'ri-settings-5-line', label:'Account Settings', path:'/account-settings', isOpen: false, children:[]},
     {icon:'ri-font-size', label:'Topography', path:'/topography', children:[]},
     {icon:'ri-login-circle-line', label:'Login/Signup', path:'/login-signup',isOpen: false,  children:[
      {icon:'', label:'Login', path:'/login-signup/login'},
      {icon:'', label:'Signup', path:'/login-signup/signup'},
      {icon:'', label:'Forgot Password', path:'/login-signup/forgot-password'},
      {icon:'', label:'Reset Password', path:'/login-signup/reset-password'},
    ]},
    {icon:'ri-alert-line', label:'Page Not Found', path:'/page-not-found',isOpen: false,  children:[]},
    {icon:'ri-auction-line', label:'Maintenance', path:'/maintenance',isOpen: false,  children:[]},
    {icon:'ri-dropdown-list', label:'Menu Level', path:'/menu-level',isOpen: false,  children:[
      {icon:'', label:'Level One Link', path:'/menu-level/level-one-link'},
      {icon:'', label:'Level One Menu', path:'/menu-level/level-one-menu', isOpen: false, children:[
        {icon:'', label:'Level Two Link', path:'/menu-level/level-one-menu/level-two-link'},
        {icon:'', label:'Level Two Menu', path:'/menu-level/level-one-menu/level-two-menu',isOpen: false,  children:[
          {icon:'', label:'Level Three Link', path:'/menu-level/level-one-menu/level-two-menu/level-three-link'},
        ]},

      ]},
    ]},
    {icon:'ri-send-plane-line', label:'External Link', path:'/external-link', isOpen: false, children:[]},
    {icon:'ri-exchange-line', label:'Chip', path:'/chip', isOpen: false, children:[]},
    {icon:'ri-ticket-line', label:'Badge', path:'/badge',isOpen: false,  children:[]},
    {icon:'ri-magic-line', label:'Disabled Link', path:'/disabled-link', isOpen: false, children:[]},
  ]
  

